"""add description to event

Revision ID: 030bfccb658a
Revises: e962318e7a9d
Create Date: 2025-07-22 19:33:01.899374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030bfccb658a'
down_revision = 'e962318e7a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
